sudo: required
services:
  - docker

before_install:
  - docker build . -t jeias/docker-reactmyi -f Dockerfile.dev

script:
  - docker run -e CI=true jeias/docker-reactmyi npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-301654787622"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id:
  secure: $AWS_ACCESS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY